// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RightPoint.Data.Generation
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DALHelperMethod : DALHelperMethodBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// ConnectionKey: ");
            
            #line 2 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\r\n// DatabaseObjectOwner: ");
            
            #line 3 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write("\r\n#region Helper Method\r\n");
            
            #line 5 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

	string delegateName = "Try" + MethodName;

	if(_memberNameCounter.ContainsKey(delegateName) == true)
	{
		_memberNameCounter[delegateName] = _memberNameCounter[delegateName] + 1;
		delegateName += _memberNameCounter[delegateName].ToString();
	}
	else
	{
		_memberNameCounter.Add(delegateName, 0);
	}

	switch ( EntityType )
	{
		case GeneratedTypes.ResultSetCollection:

            
            #line default
            #line hidden
            this.Write("#region Collection Getter Method\r\n\r\n#if UNITTEST\r\npublic partial class UnitTestDe" +
                    "legates\r\n{\r\n\tpublic delegate bool ");
            
            #line 27 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition( ");
            
            #line 27 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 27 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("RecordCollection returnValue);\r\n\tpublic static ");
            
            #line 28 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition ");
            
            #line 28 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n}\r\n#endif \r\n\r\n[StoredProcedureName(\"");
            
            #line 32 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 32 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\")]\r\npublic static bool Try");
            
            #line 33 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 33 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 33 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("RecordCollection returnValue)\r\n{\r\n\treturn WithTransaction.Try");
            
            #line 35 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(null, ");
            
            #line 35 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n}\r\n\r\npublic partial class WithTransaction\r\n{\r\n\tpublic static " +
                    "bool Try");
            
            #line 40 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(System.Data.IDbTransaction transaction, ");
            
            #line 40 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 40 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("RecordCollection returnValue)\r\n\t{\r\n#if UNITTEST\r\n\t\tif(UnitTestDelegates.");
            
            #line 43 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\treturn UnitTestDelegates.");
            
            #line 44 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 44 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n#endif\r\n\r\n\t\tint returnCode = ");
            
            #line 47 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(transaction, ");
            
            #line 47 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n\t\r\n\t\treturn returnCode == 0;\r\n\t}\r\n}\r\n\r\nprivate static int ");
            
            #line 53 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(System.Data.IDbTransaction transaction, ");
            
            #line 53 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 53 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("RecordCollection returnValue)\r\n{\r\n\tint returnCode = -1;\r\n\t\r\n\treturnValue = new ");
            
            #line 57 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("RecordCollection();\r\n\r\n\tSystem.Data.IDbConnection dbConnection = null;\r\n\t\r\n\ttry\r\n" +
                    "\t{\r\n\r\n#if QUERYLOG\r\n\t\tRightPoint.Data.QueryLogItem queryLog = RightPoint.Data.Qu" +
                    "eryLog.CreateLogItem(\"");
            
            #line 65 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 65 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 65 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\");\r\n#endif\r\n\r\n#if !DOTNET_STANDARD \r\n\t\tif (RightPoint.Data.Helper.Utilities.IsDB" +
                    "MaintenanceFileExists( \"");
            
            #line 69 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write(@""" ) == true)
        {
			returnCode = 0;
            throw new DBMaintenanceException();
        }
#endif

		if(transaction != null)
		{
			dbConnection = transaction.Connection;
		}
		else
		{
			dbConnection = RightPoint.Data.DbFactory.GetConnection( """);
            
            #line 82 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\t\t\tdbConnection.Open();\r\n\t\t}\r\n\t\r\n\t\tSystem.Data.IDbCommand dbCommand = Right" +
                    "Point.Data.DbUtility.CreateStoredProcedureCommand( dbConnection, \"");
            
            #line 86 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 86 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\r\n\t\tif(transaction != null)\r\n\t\t\tdbCommand.Transaction = transaction;\r\n\r\n");
            
            #line 91 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
 
if (CommandTimeout != null && CommandTimeout.Length > 0) 
{

            
            #line default
            #line hidden
            this.Write("\t\tdbCommand.CommandTimeout = ");
            
            #line 95 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandTimeout));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 96 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n        RightPoint.Data.DbUtility.AddReturnParameter( dbCommand );\r\n\t\t");
            
            #line 101 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateStoredProcedureParameters()));
            
            #line default
            #line hidden
            this.Write(@"

		System.Data.IDataReader dbDataReader = null;

#if QUERYLOG
		queryLog.MarkExecutionStart();
#endif

		dbDataReader = dbCommand.ExecuteReader( System.Data.CommandBehavior.CloseConnection );

#if QUERYLOG
		queryLog.MarkExecutionEnd();
#endif

		while ( dbDataReader.Read() )
		{
			returnValue.Add( new ");
            
            #line 117 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Record( ");
            
            #line 117 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateEntityConstructorParametersFromResults()));
            
            #line default
            #line hidden
            this.Write(@" ) );
		}

#if QUERYLOG
		queryLog.MarkTransformationEnd();
#endif

		dbDataReader.Close();
		returnCode = RightPoint.Data.DbUtility.GetReturnCode(dbCommand);
		
		return returnCode;
	}
	finally
	{
			if (transaction == null && dbConnection != null)
			{
				if (dbConnection.State != System.Data.ConnectionState.Closed)
				{
					dbConnection.Close();
				}

				dbConnection.Dispose();
			}
	}
	
}

#endregion

");
            
            #line 146 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

			break;
		case GeneratedTypes.OutputEntity:

            
            #line default
            #line hidden
            this.Write("#region Record Getter Method\r\n\r\n#if UNITTEST\r\npublic partial class UnitTestDelega" +
                    "tes\r\n{\r\n\tpublic delegate bool ");
            
            #line 155 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition( ");
            
            #line 155 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 155 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Record returnValue);\r\n\tpublic static ");
            
            #line 156 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition ");
            
            #line 156 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n}\r\n#endif \r\n\r\n[StoredProcedureName(\"");
            
            #line 160 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 160 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\")]\r\npublic static bool Try");
            
            #line 161 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 161 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 161 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Record returnValue)\r\n{\r\n\treturn WithTransaction.Try");
            
            #line 163 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(null, ");
            
            #line 163 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n}\r\n\r\n\r\npublic partial class WithTransaction\r\n{\r\n\tpublic stati" +
                    "c bool Try");
            
            #line 169 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(System.Data.IDbTransaction transaction, ");
            
            #line 169 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 169 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Record returnValue)\r\n\t{\r\n\r\n\t#if UNITTEST\r\n\t\tif(UnitTestDelegates.");
            
            #line 173 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\treturn UnitTestDelegates.");
            
            #line 174 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 174 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n\t#endif \r\n\r\n\t\tint returnCode = ");
            
            #line 177 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(transaction, ");
            
            #line 177 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n\t\r\n\t\tif(returnCode != 0)\r\n\t\t\treturnValue = null;\r\n\t\t\r\n\t\tretur" +
                    "n (returnCode == 0);\r\n\t}\r\n}\r\n\r\n\r\n\r\nprivate static int ");
            
            #line 188 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(System.Data.IDbTransaction transaction, ");
            
            #line 188 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 188 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Record returnValue )\r\n{\r\n\tSystem.Data.IDbConnection dbConnection = null;\r\n\t\t\r\n\ttr" +
                    "y\r\n\t{\t\r\n\r\n#if QUERYLOG\r\n\t\tRightPoint.Data.QueryLogItem queryLog = RightPoint.Dat" +
                    "a.QueryLog.CreateLogItem(\"");
            
            #line 196 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 196 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 196 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\");\r\n#endif\r\n\r\n#if !DOTNET_STANDARD\r\n\t\tif (RightPoint.Data.Helper.Utilities.IsDBM" +
                    "aintenanceFileExists( \"");
            
            #line 200 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" ) == true)\r\n        {\r\n            throw new DBMaintenanceException();\r\n       " +
                    " }\r\n#endif\r\n\r\n\t\tif(transaction != null)\r\n\t\t{\r\n\t\t\tdbConnection = transaction.Conn" +
                    "ection;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tdbConnection = RightPoint.Data.DbFactory.GetConnec" +
                    "tion( \"");
            
            #line 212 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\t\t\tdbConnection.Open();\r\n\t\t}\r\n\t\t\t\r\n\t\tSystem.Data.IDbCommand dbCommand = Rig" +
                    "htPoint.Data.DbUtility.CreateStoredProcedureCommand( dbConnection, \"");
            
            #line 216 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 216 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\r\n\t\tif(transaction != null)\r\n\t\t\tdbCommand.Transaction = transaction;\r\n\r\n");
            
            #line 221 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
 
if (CommandTimeout != null && CommandTimeout.Length > 0) 
{

            
            #line default
            #line hidden
            this.Write("\t\tdbCommand.CommandTimeout = ");
            
            #line 225 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandTimeout));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 226 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n        RightPoint.Data.DbUtility.AddReturnParameter( dbCommand );\r\n\t\t");
            
            #line 231 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateStoredProcedureParameters()));
            
            #line default
            #line hidden
            this.Write(@"

#if QUERYLOG
		queryLog.MarkExecutionStart();
#endif

		dbCommand.ExecuteNonQuery();
			
#if QUERYLOG
		queryLog.MarkExecutionEnd();
#endif

		int returnCode = RightPoint.Data.DbUtility.GetReturnCode(dbCommand);;

		switch(returnCode)
		{
			case 0:
				returnValue = new ");
            
            #line 248 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EntityName));
            
            #line default
            #line hidden
            this.Write("Record( ");
            
            #line 248 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateEntityConstructorParametersFromOutput()));
            
            #line default
            #line hidden
            this.Write(@" );
				break;
				
			default:
				returnValue = null;
				break;
		}

#if QUERYLOG
		queryLog.MarkTransformationEnd();
#endif
			
		return returnCode;
	}
	finally
	{
		if (transaction == null && dbConnection != null)
		{
			if (dbConnection.State != System.Data.ConnectionState.Closed)
			{
				dbConnection.Close();
			}

			dbConnection.Dispose();
		}
	}
}

#endregion

");
            
            #line 278 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

			break;
	case GeneratedTypes.SimpleType:

            
            #line default
            #line hidden
            this.Write("#region SimpleType Getter Method\r\n\r\n#if UNITTEST\r\npublic partial class UnitTestDe" +
                    "legates\r\n{\r\n\tpublic delegate bool ");
            
            #line 287 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition( ");
            
            #line 287 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 287 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnValueTypeForSimpleType()));
            
            #line default
            #line hidden
            this.Write(" returnValue);\r\n\tpublic static ");
            
            #line 288 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition ");
            
            #line 288 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n}\r\n#endif\r\n\r\n[StoredProcedureName(\"");
            
            #line 292 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 292 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\")]\r\npublic static bool Try");
            
            #line 293 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 293 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 293 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnValueTypeForSimpleType()));
            
            #line default
            #line hidden
            this.Write(" returnValue )\r\n{\r\n\treturn WithTransaction.Try");
            
            #line 295 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(null, ");
            
            #line 295 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n}\r\n\r\npublic partial class WithTransaction\r\n{\r\n\tpublic static " +
                    "bool Try");
            
            #line 300 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(System.Data.IDbTransaction transaction, ");
            
            #line 300 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 300 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnValueTypeForSimpleType()));
            
            #line default
            #line hidden
            this.Write(" returnValue)\r\n\t{\r\n\r\n#if UNITTEST\r\n\t\tif(UnitTestDelegates.");
            
            #line 304 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\treturn UnitTestDelegates.");
            
            #line 305 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 305 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n#endif\r\n\t\t\r\n\t\tint returnCode = ");
            
            #line 308 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(transaction, ");
            
            #line 308 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" out returnValue);\r\n\t\r\n\t\treturn (returnCode == 0);\r\n\t}\r\n}\r\n\r\nprivate static int ");
            
            #line 314 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(System.Data.IDbTransaction transaction, ");
            
            #line 314 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" out ");
            
            #line 314 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnValueTypeForSimpleType()));
            
            #line default
            #line hidden
            this.Write(" returnValue )\r\n{\r\n\treturnValue = null;\r\n\t\r\n\tSystem.Data.IDbConnection dbConnecti" +
                    "on = null;\r\n\t\t\r\n\ttry\r\n\t{\t\r\n\r\n#if QUERYLOG\r\n\t\tRightPoint.Data.QueryLogItem queryL" +
                    "og = RightPoint.Data.QueryLog.CreateLogItem(\"");
            
            #line 324 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 324 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 324 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\");\r\n#endif\r\n\r\n#if !DOTNET_STANDARD\r\n\t\tif (RightPoint.Data.Helper.Utilities.IsDBM" +
                    "aintenanceFileExists( \"");
            
            #line 328 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" ) == true)\r\n        {\r\n            throw new DBMaintenanceException();\r\n       " +
                    " }\r\n#endif \r\n\r\n\t\tif(transaction != null)\r\n\t\t{\r\n\t\t\tdbConnection = transaction.Con" +
                    "nection;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tdbConnection = RightPoint.Data.DbFactory.GetConne" +
                    "ction( \"");
            
            #line 340 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\t\t\tdbConnection.Open();\r\n\t\t}\r\n\r\n\t\tSystem.Data.IDbCommand dbCommand = RightP" +
                    "oint.Data.DbUtility.CreateStoredProcedureCommand( dbConnection, \"");
            
            #line 344 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 344 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\" );\r\n            \r\n\t\tif(transaction != null)\r\n\t\t\tdbCommand.Transaction = transac" +
                    "tion;\r\n\r\n\r\n");
            
            #line 350 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
 
if (CommandTimeout != null && CommandTimeout.Length > 0) 
{

            
            #line default
            #line hidden
            this.Write("\t\tdbCommand.CommandTimeout = ");
            
            #line 354 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandTimeout));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 355 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

}

            
            #line default
            #line hidden
            this.Write("            \r\n            \r\n        RightPoint.Data.DbUtility.AddReturnParameter(" +
                    " dbCommand );\r\n\t\t");
            
            #line 360 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateStoredProcedureParameters()));
            
            #line default
            #line hidden
            this.Write(@"

#if QUERYLOG
		queryLog.MarkExecutionStart();
#endif
			
		dbCommand.ExecuteNonQuery();

#if QUERYLOG
		queryLog.MarkExecutionEnd();
#endif

		int returnCode = RightPoint.Data.DbUtility.GetReturnCode(dbCommand);
            
		if(returnCode == 0)
			returnValue = ");
            
            #line 375 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateReturnValueForSimpleType()));
            
            #line default
            #line hidden
            this.Write(@";

#if QUERYLOG
		queryLog.MarkTransformationEnd();
#endif
				
		return returnCode;
	}
	finally
	{
			if (transaction == null && dbConnection != null)
			{
				if (dbConnection.State != System.Data.ConnectionState.Closed)
				{
					dbConnection.Close();
				}

				dbConnection.Dispose();
			}
	}
}
#endregion

");
            
            #line 398 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"


			break;
		case GeneratedTypes.ReturnValue:

            
            #line default
            #line hidden
            this.Write("#region ReturnValue Getter Method\r\n\r\n#if UNITTEST\r\npublic partial class UnitTestD" +
                    "elegates\r\n{\r\n\tpublic delegate bool ");
            
            #line 408 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition( ");
            
            #line 408 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, false)));
            
            #line default
            #line hidden
            this.Write(" );\r\n\tpublic static ");
            
            #line 409 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("UnitTestDelegateDefinition ");
            
            #line 409 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" = null;\r\n}\r\n#endif\r\n\r\n[StoredProcedureName(\"");
            
            #line 413 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 413 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\")]\r\npublic static bool Try");
            
            #line 414 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 414 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, false)));
            
            #line default
            #line hidden
            this.Write(" )\r\n{\r\n\treturn WithTransaction.Try");
            
            #line 416 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 416 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" null );\r\n}\r\n\r\npublic partial class WithTransaction\r\n{\r\n\tpublic static bool Try");
            
            #line 421 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("( ");
            
            #line 421 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" System.Data.IDbTransaction transaction)\r\n\t{\r\n\r\n#if UNITTEST\r\n\t\tif(UnitTestDelega" +
                    "tes.");
            
            #line 425 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write(" != null)\r\n\t\t\treturn UnitTestDelegates.");
            
            #line 426 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(delegateName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 426 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, false)));
            
            #line default
            #line hidden
            this.Write(");\r\n#endif\r\n\t\t\r\n\t\tint returnValue = ");
            
            #line 429 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 429 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(false, true)));
            
            #line default
            #line hidden
            this.Write(" transaction );\r\n\t\r\n\t\treturn (returnValue == 0);\r\n\t}\r\n}\r\n\r\n\r\nprivate static Syste" +
                    "m.Int32 ");
            
            #line 436 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MethodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 436 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateMethodParameters(true, true)));
            
            #line default
            #line hidden
            this.Write(" System.Data.IDbTransaction transaction )\r\n{\r\n\tSystem.Data.IDbConnection dbConnec" +
                    "tion = null;\r\n\t\t\r\n\ttry\r\n\t{\t\r\n\r\n#if QUERYLOG\r\n\t\tRightPoint.Data.QueryLogItem quer" +
                    "yLog = RightPoint.Data.QueryLog.CreateLogItem(\"");
            
            #line 444 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 444 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 444 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\");\r\n#endif\r\n\r\n#if !DOTNET_STANDARD\r\n\t\tif (RightPoint.Data.Helper.Utilities.IsDBM" +
                    "aintenanceFileExists( \"");
            
            #line 448 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" ) == true)\r\n        {\r\n            throw new DBMaintenanceException();\r\n       " +
                    " }\r\n#endif\r\n\r\n\t\tif(transaction != null)\r\n\t\t{\r\n\t\t\tdbConnection = transaction.Conn" +
                    "ection;\r\n\t\t}\r\n\t\telse\r\n\t\t{\r\n\t\t\tdbConnection = RightPoint.Data.DbFactory.GetConnec" +
                    "tion( \"");
            
            #line 460 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((ConnectionKey == null) ? Database : ConnectionKey));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\t\t\tdbConnection.Open();\r\n\t\t}\r\n\r\n\t\tSystem.Data.IDbCommand dbCommand = RightP" +
                    "oint.Data.DbUtility.CreateStoredProcedureCommand( dbConnection, \"");
            
            #line 464 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DatabaseObjectOwner));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 464 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StoredProcedureName));
            
            #line default
            #line hidden
            this.Write("\" );\r\n\r\n\t\tif(transaction != null)\r\n\t\t\tdbCommand.Transaction = transaction;\r\n\r\n");
            
            #line 469 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
 
if (CommandTimeout != null && CommandTimeout.Length > 0) 
{

            
            #line default
            #line hidden
            this.Write("\t\tdbCommand.CommandTimeout = ");
            
            #line 473 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CommandTimeout));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 474 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

}

            
            #line default
            #line hidden
            this.Write("\r\n        RightPoint.Data.DbUtility.AddReturnParameter( dbCommand );\r\n\t\t");
            
            #line 479 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GenerateStoredProcedureParameters()));
            
            #line default
            #line hidden
            this.Write(@"

#if QUERYLOG
		queryLog.MarkExecutionStart();
#endif

		dbCommand.ExecuteNonQuery();

#if QUERYLOG
		queryLog.MarkExecutionEnd();
#endif


#if QUERYLOG
		queryLog.MarkTransformationEnd();
#endif

		return RightPoint.Data.DbUtility.GetReturnCode(dbCommand);
	}
	finally
	{
		if (transaction == null && dbConnection != null)
		{
			if (dbConnection.State != System.Data.ConnectionState.Closed)
			{
				dbConnection.Close();
			}

			dbConnection.Dispose();
		}
	}
}
#endregion
");
            
            #line 512 "C:\source\Learn\RightPoint\Movies\RightPoint.Framework\EventInventory\_Source\Data\Generation\DALHelperMethod.tt"

			break;
	}

            
            #line default
            #line hidden
            this.Write("\r\n#endregion\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class DALHelperMethodBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
